# Generated by Django 4.0.4 on 2022-05-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStart', models.BooleanField(default=False)),
                ('roomtitle', models.CharField(max_length=50)),
                ('roomdetail', models.CharField(max_length=300)),
                ('persons', models.IntegerField(default=0)),
                ('personlimit', models.IntegerField(default=0)),
                ('endtime', models.DateTimeField()),
                ('linkURL', models.TextField()),
                ('roomTimeStr', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
